# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("JARVIS")
        MainWindow.resize(960, 500)
        MainWindow.setMinimumSize(QtCore.QSize(720, 480))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 160, 35, 10))
        self.label.setObjectName("label")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setEnabled(False)
        self.background.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.background.setText("")
        self.background.setObjectName("background")
        self.core = QtWidgets.QLabel(self.centralwidget)
        self.core.setGeometry(QtCore.QRect(160, 0, 551, 371))
        self.core.setText("")
        self.core.setPixmap(QtGui.QPixmap(".\\reactor4.gif"))
        self.core.setObjectName("core")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(810, 20, 120, 50))
        self.start.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.start.setObjectName("start")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(810, 100, 120, 50))
        self.exit.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.exit.setObjectName("exit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 400, 35, 10))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330 , 400, 251, 71))
        self.label_2.setStyleSheet("\n"
"color: rgb(0, 255, 255);\n"
"font: 81 72pt \"Rockwell Extra Bold\";\n"
"font: 72pt \"Times New Roman\";\n"
"font: 72pt \"Lucida Bright\";\n"
"font: 72pt \"Georgia\";")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\name.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.start.setText(_translate("MainWindow", "START"))
        self.exit.setText(_translate("MainWindow", "EXIT"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
